baseURL = 'https://islamophobia-hotline.netlify.app/'
languageCode = 'en-ca'
title = 'Islamophobia Legal Assistance Hotline'


theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "news"

[params]
  author = "Access Probono"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-light-red"
  text_color = "black"
  body_classes = "avenir bg-light-silver"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/islamophobia_hotline"